### ISSUE TITLE
Update the example of workflow in the README

### ISSUE THREAD

**Issue by patoroco** [patoroco/doorkeeper#2]
The current README shows how to use the action in the same repository (in this one). It should be updated with the specific name of action:

```yaml
- name: Doorman open
  uses: patoroco/doorman@master
  with:
    digitaloceanToken: ${{ secrets.DO_TOKEN }}
    firewallName: "my_firewall"
    actionToDo: "add"
```
